// Draws the favicon, rather than anybody placing the points by hand.
//
// The mark is a d20 seen down a face, which is also exactly a node graph: a
// central triangle of three pins, a hexagonal ring of six, and the yarn between
// them. Fifteen edges, nine nodes — the visible half of the icosahedron.
//
// Writes `public/favicon.svg`. Run with `node scripts/generate-favicon.mjs`.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

/** The icon's own units. `viewBox` is square, so everything is a fraction of this. */
const SIZE = 32;
const CENTRE = SIZE / 2;

const PHI = (1 + Math.sqrt(5)) / 2;

/** Radius of the hexagonal ring. */
const RING_RADIUS = 13.2;

/**
 * Radius of the triangle inside it, which is not a free choice: projecting an
 * icosahedron down a face puts the front face's vertices at exactly 1/φ of the
 * ring's. Any other ratio is a triangle in a hexagon, not a die.
 */
const CORE_RADIUS = RING_RADIUS / PHI;

/** A node's radius, and the weight of the yarn. */
const NODE_RADIUS = 1.75;
const YARN_WIDTH = 1.6;

/**
 * Stuck on at an angle, as everything on the board is. Anticlockwise, which in
 * SVG's coordinates — y growing downwards — is the negative way round. Enough
 * to look deliberate at 16px, not enough to read as a mistake.
 */
const TILT = -8;

const DEGREES = Math.PI / 180;

/** Angles run anticlockwise from due east, as they do in maths; SVG's y grows down. */
function onCircle(radius, degrees) {
  return {
    x: CENTRE + radius * Math.cos(degrees * DEGREES),
    y: CENTRE - radius * Math.sin(degrees * DEGREES),
  };
}

const round = (n) => Math.round(n * 100) / 100;

// Point-up: one vertex at the top, then every 60°. The triangle takes every
// other direction, so each of its vertices sits under a ring vertex and its
// edges come down between the two beside it — which is what makes the figure
// read as a die rather than as a wheel.
const RING_ANGLES = [90, 150, 210, 270, 330, 30];
const CORE_ANGLES = [90, 210, 330];

const ring = RING_ANGLES.map((angle) => onCircle(RING_RADIUS, angle));
const core = CORE_ANGLES.map((angle) => onCircle(CORE_RADIUS, angle));

/** The vertices, keyed by the direction they lie in, so the yarn can name them. */
const node = new Map();
RING_ANGLES.forEach((angle, index) => node.set(`ring:${angle}`, ring[index]));
CORE_ANGLES.forEach((angle, index) => node.set(`core:${angle}`, core[index]));

const yarn = [];
const tie = (a, b) => yarn.push([node.get(a), node.get(b)]);

// The ring closes on itself.
RING_ANGLES.forEach((angle, index) =>
  tie(`ring:${angle}`, `ring:${RING_ANGLES[(index + 1) % 6]}`),
);
// The triangle closes on itself.
CORE_ANGLES.forEach((angle, index) =>
  tie(`core:${angle}`, `core:${CORE_ANGLES[(index + 1) % 3]}`),
);
// Each core vertex reaches the two ring vertices beside it — the three faces
// that are turned towards the viewer.
CORE_ANGLES.forEach((angle) => {
  tie(`core:${angle}`, `ring:${(angle + 60) % 360}`);
  tie(`core:${angle}`, `ring:${(angle + 300) % 360}`);
});

const line = ([from, to]) =>
  `    <line x1="${round(from.x)}" y1="${round(from.y)}" x2="${round(to.x)}" y2="${round(to.y)}" />`;

// Every vertex is drawn, including the three bare ring vertices that carry no
// yarn to the middle: a graph reads as a graph because its nodes are visible.
const dot = (point) =>
  `  <circle cx="${round(point.x)}" cy="${round(point.y)}" r="${NODE_RADIUS}" />`;

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${SIZE} ${SIZE}" width="${SIZE}" height="${SIZE}" role="img" aria-label="Diagrams &amp; Dossiers">
  <!-- Generated by scripts/generate-favicon.mjs. Edit that, not this. -->
  <title>Diagrams &amp; Dossiers</title>
  <style>
    /* No background, and no single colour that reads on both a light and a dark
       tab strip: the ink of the board on the one, its parchment on the other. */
    svg { color: #2e1f14 }
    @media (prefers-color-scheme: dark) { svg { color: #e3d2ae } }
  </style>
  <g transform="rotate(${TILT} ${CENTRE} ${CENTRE})">
    <g fill="none" stroke="currentColor" stroke-width="${YARN_WIDTH}" stroke-linecap="round">
${yarn.map(line).join("\n")}
    </g>
    <g fill="currentColor">
${[...ring, ...core].map(dot).join("\n")}
    </g>
  </g>
</svg>
`;

const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, "..", "public", "favicon.svg");
writeFileSync(target, svg);
console.log(
  `wrote ${target} — ${yarn.length} edges, ${ring.length + core.length} nodes`,
);
